### ISSUE TITLE
can i get the dataset you uses

### ISSUE THREAD

**Issue by Hx96** [SystemErrorWang/CartoonGAN#5]
i want implement the code you write.can i get the dataset link

**Comment by SystemErrorWang** [comment]
> i want implement the code you write.can i get the dataset link

I am sorry that due to copyright issues, i may not be able to share, but i can give you some advice:
For human face: ffhq dataset or celeba hq(resize to 256*256)
For animate face: kyoto animate and pa works, use animate face detection and manually clean them
For real world photo: CycleGAN training dataset
For animate image: Shinkai Makoto, Hosoda Mamoru, Miyazaki Hayao, get key frames and random crop to 256256 (if you manually clean them you may get better result)
